<?php


/**
 * Implements hook_menu().
 */
function fitmoo_admintools_menu() {
  $items = array();
  

  $items['user/%user/moola'] = array(
    'title' => 'Moola',
    'page callback' => 'fitmoo_admintools_moola',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['moola/migrate'] = array(
    'title' => 'Moola',
    'page callback' => '_migrate_moola',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'weight' => 1,
  );

  
  return $items;
}

function fitmoo_admintools_moola($user){
	//pending
   	$q = db_select('fitmoo_user_accounting', 'a')
  	    ->fields('a')
  		->condition('uid', $user->uid,'=')
		->condition('status','pending','=');
	$q->addExpression('SUM(ammount)', 'ammount');	
  	$result = $q->execute()->fetchAssoc();
	
	$pending = $result['ammount'];
	
	//cleared
   	$q = db_select('fitmoo_user_accounting', 'a')
  	    ->fields('a')
  		->condition('uid', $user->uid,'=')
		->condition('status','cleared','=');
	$q->addExpression('SUM(ammount)', 'ammount');	
  	$result = $q->execute()->fetchAssoc();
	
	$cleared = $result['ammount'];
 
    $total = $cleared + $pending;

	
	$header = array(
		array('data' => t('Type')),
		array('data' => t('Ammount')),
	);
    $row[] = array(
    	array('data' => t('<b>Pending</b>')),
		array('data' => t('$'.number_format( $pending, 2, ".", "," ))),
    );
    $row[] = array(
    	array('data' => t('<b>Total Value</b>')),
		array('data' => t('$'.number_format( $total, 2, ".", "," ))),
    );
    $row[] = array(
    	array('data' => t('<b>Available</b>')),
		array('data' => t('$'.number_format( $cleared, 2, ".", "," ))),
    );
    
	$data = array(
		'header' => $header,
		'rows' => $row,
	);
	return theme('table',$data);
	
}



      	
	   


function _migrate_moola(){

  	    $q = db_select('fitmoo_user_accounting', 's');
 		// ->condition('SESSION', $ses_id,'=')
 		// ->condition('step', 'planfeatures','=')
		$q->addExpression('distinct(uid)', 'uid');	
	  	$result = $q->execute()->fetchAllAssoc('uid');




    foreach($result as $data){
    	
		_update_user_balance($data->uid);
		
		
    }

    return;
	
}

function _update_user_balance($uid){
	
   	$q = db_select('fitmoo_user_accounting', 'a')
  	    ->fields('a')
  		->condition('uid', $uid,'=')
		->condition('status','pending','=');
	$q->addExpression('SUM(ammount)', 'ammount');	
  	$result = $q->execute()->fetchAssoc();

	$pending = $result['ammount'];

	//cleared
   	$q = db_select('fitmoo_user_accounting', 'a')
  	    ->fields('a')
  		->condition('uid', $uid,'=')
		->condition('status','cleared','=');
	$q->addExpression('SUM(ammount)', 'ammount');	
  	$result = $q->execute()->fetchAssoc();

	$cleared = $result['ammount'];
	
	
	//total
   	$q = db_select('fitmoo_user_accounting', 'a')
  	    ->fields('a')
  		->condition('uid', $uid,'=');
	$q->addExpression('SUM(ammount)', 'ammount');	
  	$result = $q->execute()->fetchAssoc();

	$total = $result['ammount'];
	
	$user = user_load($uid);
	
	$user->field_balance_pending['und'][0]['value'] = $pending;
	$user->field_balance_available['und'][0]['value'] = $cleared;
    $user->field_balance_total['und'][0]['value'] = $total;		
	user_save($user);
	
}
	
	
	
	
